name: Jira Label

on:
  push:
    branches: [ develop, development, jod_main_development, canary, master, main ]

jobs:
  label-jiras:
    uses: talktala/.github/.github/workflows/jira-label.yml@master
    secrets: inherit
