name: 'PR name check'
on:
  pull_request:
    types:
      # Check title when opened.
      - opened
      # Check title when new commits are pushed.
      # Required to use as a status check.
      - synchronize
      # Check when the pr is edited
      - edited

jobs:
  pr-name-check:
    uses: talktala/.github/.github/workflows/pr-name-check.yml@master
    secrets: inherit
