name: Qovery Environment Cleanup

on: workflow_call

jobs:
  mime-environment-removal:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - id: delete-environment
        name: Remove mime environment
        env:
          QOVERY_CLI_ACCESS_TOKEN: ${{ secrets.QOVERY_CLI_ACCESS_TOKEN }}
        run: |
          curl -s https://get.qovery.com | bash

          echo "Organization name: ${{ vars.QOVERY_ORGANIZATION_NAME }}"
          echo "Project name: ${{ vars.QOVERY_PROJECT_NAME }}"

          branch="${{ github.event.ref }}"
          echo "Deleted branch:"
          echo "$branch"

          epic_name="${branch#mime/}"
          environment_name_upper="${epic_name//[^a-zA-Z0-9\-_]/}"
          environment_name="${environment_name_upper,,}"

          delete_ok=True
          found_branch=''
          repos=('talkspace-api' 'quickmatch-api' 'auth-api' 'sns-services-api' 'backoffice-web' 'talkspace-web' 'surveys' 'cron-service')
          for repo in "${repos[@]}"; do
            repo_branch=$(curl -s -H "Authorization: token ${{ secrets.GIT_TOKEN }}" \
              -X GET "https://api.github.com/repos/talktala/${repo}/branches/${branch}")
            if [[ $(echo "$repo_branch" | jq '.name') == \"$branch\" ]]; then
              echo "Found matching branch:"
              echo $branch
              delete_ok=False
              found_branch=$repo
              break
            fi
          done

          q_environs=`qovery environment list \
            --organization "${{ vars.QOVERY_ORGANIZATION_NAME }}" \
            --project "${{ vars.QOVERY_PROJECT_NAME }}" \
            --json`
          env_exists=$(echo "$q_environs" | jq ".[] | select(.name == \"$environment_name\")")

          if [[ -n "$env_exists" && "$delete_ok" == "True" ]]; then
            echo "Mime $environment_name environment exists, found no epic branches in other repos, deleting"
            qovery environment delete \
              --organization "${{ vars.QOVERY_ORGANIZATION_NAME }}" \
              --project "${{ vars.QOVERY_PROJECT_NAME }}" \
              --environment "$environment_name" \
              -w
          elif [[ -n "$env_exists" ]]; then
            echo "Mime environment $environment_name exists, but a matching branch was found in $found_branch."
            echo "Mime environment will be deleted when no matching branches are found"
          else
            echo "No Mime environment found matching $branch"
          fi
