name: 'PR name check'

on: workflow_call

jobs:
  pr-name-check:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          # Match pull request titles in the form of:
          # Release/s123
          # canary => dev
          # master => dev
          # main => dev
          # fix: MOBILE-123123 - fix bug
          # feat: NYC-123123 - fix bug
          # perf: MOBILE-123123 - fix bug
          # MOBILE-123123 - fix bug
          # MOBILE-123123 MOBILE-34534 - fix bug
          # hotfix/MOBILE-123123 - fix sueprbug
          # Revert "MOBILE-123123 - revert because Lu didn't like it"
          # Revert "perf: MOBILE-123123 - fix bug"
          regex: '^(Revert\s\"?)?(((dev|canary|master|main)\s=>\sdev)|Release\/s\d+|(hotfix\/|fix:\s|feat:\s|perf:\s)?((${{ vars.JIRA_PATTERN }})-\d*)|Lokalise:.+)'
